In [ ]:
l=[1,2,3,4,5]

In [ ]:
print(l)

[1, 2, 3, 4, 5]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
a.shape

(5,)

In [ ]:
b=np.array(([1,2,3,4],[5,6,7,8]))
b.shape

(2, 4)

In [ ]:
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
x=np.zeros((4,5))

In [ ]:
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
y=np.ones((3,3))

In [ ]:
y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
z=np.full((5,4),2)
z

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [ ]:
a=np.eye(6)

In [ ]:
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
k=np.random.random((3,4))

In [ ]:
k

array([[0.12218299, 0.44600873, 0.5509648 , 0.04071394],
       [0.40968875, 0.39135182, 0.38956543, 0.03660113],
       [0.19046993, 0.08132251, 0.07109551, 0.3847203 ]])

In [ ]:
t=np.random.randint(10,100,(2,5))
t

array([[22, 68, 90, 30, 62],
       [25, 61, 23, 15, 58]])

In [ ]:
d=np.linspace(10,40,3)
d

array([10., 25., 40.])

In [ ]:
k=np.arange(10,30,2)
k

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
l=[2,3,4,6]

In [ ]:
nparr=np.asarray(l)

In [ ]:
nparr

array([2, 3, 4, 6])

In [ ]:
type(nparr)

numpy.ndarray

In [ ]:
nparr.shape

(4,)

In [ ]:
nparr.ndim

1

In [ ]:
nparr.dtype

dtype('int64')

In [ ]:
l=[1,2,3,4]

In [ ]:
l1=[3,4,5,6]

In [ ]:
l1+l2

NameError: name 'l2' is not defined

In [ ]:
l+l1

[1, 2, 3, 4, 3, 4, 5, 6]

In [ ]:
a=np.random.randint(10,50,(2,3))

In [ ]:
b=np.random.randint(10,50,(2,3))
print(a)

[[12 34 14]
 [17 46 25]]


In [ ]:
print(b)

[[36 24 21]
 [19 42 21]]


In [ ]:
print(a+b)

[[48 58 35]
 [36 88 46]]


In [ ]:
print(a-b)

[[-24  10  -7]
 [ -2   4   4]]


In [ ]:
print(a*b)

[[ 432  816  294]
 [ 323 1932  525]]


In [ ]:
print(a/2)

[[ 6.  17.   7. ]
 [ 8.5 23.  12.5]]


In [ ]:
print(np.add(a,b))

[[48 58 35]
 [36 88 46]]


In [ ]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0, *, device=None)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so th

In [ ]:
a=np.random.randint(2,15,(2,4))

In [ ]:
a

array([[ 8,  5, 14,  6],
       [ 2, 12,  2,  5]])

In [ ]:
k=np.transpose(a)

In [ ]:
k

array([[ 8,  2],
       [ 5, 12],
       [14,  2],
       [ 6,  5]])

In [ ]:
p=k.reshape(8,1)

In [ ]:
p

array([[ 8],
       [ 2],
       [ 5],
       [12],
       [14],
       [ 2],
       [ 6],
       [ 5]])

In [ ]:
p=p.astype(int)

In [ ]:
p.dtype

dtype('int64')

In [ ]:
p=625
np.sqrt(p)

np.float64(25.0)

In [ ]:
p=np.array([1,4,5,6])
np.sin(p)

array([ 0.84147098, -0.7568025 , -0.95892427, -0.2794155 ])

In [ ]:
np.cos(p)

array([ 0.54030231, -0.65364362,  0.28366219,  0.96017029])

In [ ]:
np.tan(p)

array([ 1.55740772,  1.15782128, -3.38051501, -0.29100619])

In [ ]:
p=np.array([3.4,5.6,7.8])
np.floor(p)

array([3., 5., 7.])

In [ ]:
np.ceil(p)

array([4., 6., 8.])

In [ ]:
k=np.array([2,3,4,5])
k[1:3]

array([3, 4])

In [ ]:
k[::]

array([2, 3, 4, 5])

In [ ]:
k[-1]

np.int64(5)

In [ ]:
k[2:]

array([4, 5])

In [ ]:
np.exp(k)

array([  7.3890561 ,  20.08553692,  54.59815003, 148.4131591 ])

In [ ]:
a=np.array([1,2,3,4])

In [ ]:
np.mean(a)



np.float64(2.5)

In [ ]:
np.median(a)

np.float64(2.5)

In [ ]:
np.std(a)

np.float64(1.118033988749895)

In [ ]:
np.sum(a)

np.int64(10)

In [ ]:
np.min(a)

np.int64(1)

In [ ]:
np.max(a)

np.int64(4)

In [ ]:
np.argmin(a)

np.int64(0)

In [ ]:
np.argmax(a)

np.int64(3)

In [ ]:
k=a[::-1]

In [ ]:
k

array([4, 3, 2, 1])

In [ ]:
print(k.sort())

None


In [ ]:
k

array([1, 2, 3, 4])

In [ ]:
np.argsort(k)

array([0, 1, 2, 3])

In [ ]:
k=np.array([3,1,5,4])

In [ ]:
k.sort()

In [ ]:
k

array([1, 3, 4, 5])

In [ ]:
k.argsort()


array([0, 1, 2, 3])

In [ ]:
np.nonzero(k)

(array([0, 1, 2, 3]),)

In [ ]:
a=np.array([[1,2],[4,5]])

In [ ]:
np.linalg.inv(a)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [ ]:
np.linalg.det(a)

np.float64(-2.9999999999999996)

In [ ]:
vals,vecs=np.linalg.eig(a)

In [ ]:
print(vals)

[-0.46410162  6.46410162]


In [ ]:
print(vecs)

[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


In [ ]:
np.save

<function save at 0x7da8d43b50f0>